---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    which: ansible_distribution == "CentOS"
  - name: install apache and php packages 
    service:
      name: 
        - httpd
        - php
      state: latest
   which: ansible_distribution == "CentOS"

